spring:
  application:
    name: Config-dev
    
eureka:
  instance:
    prefer-ip-addres: true
  client:
    fetch-registry: true
    registrer-with-eureka: true
    server-url:
      defaulZone: http://localhost:8761/eureka
